version: "4.31.1"

services:
  app:
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - 0.0.0.0:8080
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - .env
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ./mysite:/app/database
