# Generated by Django 3.2.3 on 2021-06-23 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folksongs', '0002_song'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='name',
        ),
        migrations.AddField(
            model_name='song',
            name='songAuthor',
            field=models.CharField(default='SOME AUTHOR', max_length=30),
        ),
        migrations.AddField(
            model_name='song',
            name='songID',
            field=models.CharField(default='SOME ID', max_length=30),
        ),
        migrations.AddField(
            model_name='song',
            name='songName',
            field=models.CharField(default='SOME NAME', max_length=30),
        ),
        migrations.AlterField(
            model_name='song',
            name='description',
            field=models.TextField(),
        ),
    ]
