# Generated by Django 3.2.3 on 2021-06-24 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folksongs', '0003_auto_20210623_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='songAuthor',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='song',
            name='songName',
            field=models.TextField(),
        ),
    ]
