# Generated by Django 3.2.3 on 2021-06-28 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folksongs', '0004_auto_20210624_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songImage',
            field=models.ImageField(default='SOME IMG', upload_to=''),
        ),
    ]
