# Generated by Django 3.2.3 on 2021-06-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folksongs', '0005_song_songimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='songImage',
        ),
        migrations.AddField(
            model_name='song',
            name='image',
            field=models.ImageField(default='some img', upload_to='images'),
        ),
    ]
