# Generated by Django 3.2.3 on 2021-06-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folksongs', '0006_auto_20210628_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='path/', verbose_name='img'),
        ),
    ]
