# Generated by Django 3.2.4 on 2021-06-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folksongs', '0009_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
