# Generated by Django 3.2.4 on 2021-06-30 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('folksongs', '0010_alter_song_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('song', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='folksongs.song')),
            ],
        ),
    ]
