# Generated by Django 3.2.4 on 2021-06-30 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folksongs', '0011_postimage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='SongImage',
        ),
    ]
