# Generated by Django 3.2.4 on 2021-07-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folksongs', '0012_rename_postimage_songimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='songGenre',
            field=models.TextField(default='SOME GENRE'),
        ),
        migrations.AddField(
            model_name='song',
            name='songVolume',
            field=models.TextField(default='SOME VOLUME'),
        ),
    ]
